### ISSUE TITLE
"cannot parse"

### ISSUE THREAD

**Issue by AtomicNess123** [grantmcwilliams/Workflowy2Mindmap#1]
Hi! 

Excellent tool! Just that I am getting this warning after running it on Terminal: 

```
failed to load external entity "workflowy2mm.sh/opml2mm.xsl"
cannot parse workflowy2mm.sh/opml2mm.xsl
```

**Comment by grantmcwilliams** [comment]
Is the opml2mm.xsl file in the same directory as the script? The script calls the opml2mm.xsl file from the CMDPATH variable. Cd into the directory where both files are and run it from there.

**Comment by AtomicNess123** [comment]
Yes, it is.

```bash
§ ~/Downloads/Workflowy2Mindmap-master > ls -la
total 88

drwxrwxr-x@  8 user   256B 10 Dec 21:56 ./
drwx------+ 30 user   960B 10 Dec 21:31 ../
-rw-r--r--@  1 user   6.0K 10 Dec 21:56 .DS_Store
-rw-rw-r--@  1 user    18K 12 Jan  2016 LICENSE
-rw-rw-r--@  1 user   2.2K 12 Jan  2016 README.md
-rw-rw-r--@  1 user   2.4K 12 Jan  2016 opml2mm.xsl
-rw-rw-r--@  1 user   2.8K 10 Dec 15:21 test.opml
-rwxr-xr-x@  1 user   1.2K 12 Jan  2016 workflowy2mm.sh*
§ ~/Downloads/Workflowy2Mindmap-master > bash workflowy2mm.sh test.opml                                                                 
warning: failed to load external entity "workflowy2mm.sh/opml2mm.xsl"
cannot parse workflowy2mm.sh/opml2mm.xsl
```

**Comment by grantmcwilliams** [comment]
Hmmm, apparently the variable isn't being populated with what I think it
should. You could edit the workflowy2mm.sh script and change $CMDDIR to ./

XSLFILE="./opml2mm.xsl"

That will work. I'm not sure why CMDDIR isn't getting populated.

Grant McWilliams
http://grantmcwilliams.com/

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

**Comment by AtomicNess123** [comment]
Perfect, now it works! For some reason CMDDIR is empty. Could it be that I'm on a mac? Anyway, thanks so much! I close the issue.
